name: Deploy MultiDocker
on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - run: docker build -t guillesanz21/courses.dockerk8.react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true guillesanz21/courses.dockerk8.react-test npm test

  publish-to-dockerhub:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - run: docker build -t guillesanz21/courses.dockerk8.multi-client ./client
      - run: docker build -t guillesanz21/courses.dockerk8.multi-nginx ./nginx
      - run: docker build -t guillesanz21/courses.dockerk8.multi-server ./server
      - run: docker build -t guillesanz21/courses.dockerk8.multi-worker ./worker

      - run: docker push guillesanz21/courses.dockerk8.multi-client
      - run: docker push guillesanz21/courses.dockerk8.multi-nginx
      - run: docker push guillesanz21/courses.dockerk8.multi-server
      - run: docker push guillesanz21/courses.dockerk8.multi-worker

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v3

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: fibonacci-test
          environment_name: Fibonacci-test-env
          existing_bucket_name: elasticbeanstalk-eu-west-2-423236424530
          region: eu-west-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
